version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:ap-southeast-2:430302018311:task-definition/bluegreen-task:2"
       LoadBalancerInfo:
         ContainerName: "bluegreen"
         ContainerPort: 80
